/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pms.frames;

import com.pms.daoimpl.CompanyDAOImpl;
import com.pms.daoimpl.ProductDAOImpl;
import com.pms.daoimpl.UnitDAOImpl;
import com.pms.models.CompanyModel;
import com.pms.models.ProductModel;
import com.pms.models.UnitModel;
import com.pms.utility.MyDateFormatter;

import java.sql.Timestamp;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author farhan baloch
 */
public class ProductAddFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddProductFrame
     */
    public ProductAddFrame() {
        initComponents();
        fillCompanyComboBox();
        fillUnitComboBox();
        this.setLocationRelativeTo(null);
    }
    public void clearAllFeilds()
    {
      txtName.setText("");
      txtCost.setText("");
      txtPrice.setText("");
      txtQuantity.setText("");
      txtNumber.setText("");
//      expiryDate.setText("");
    }       
   public void addProduct() {
        if(txtName.getText().equals("")||txtCost.getText().equals("")||txtPrice.getText().equals("")||txtQuantity.getText().equals("")||txtNumber.getText().equals("")){
         JOptionPane.showMessageDialog(this, "Any Field Could not be empty");
        }
        else{

        String name = txtName.getText().toString();
        String cost = txtCost.getText().toString();
        double costdouble = Double.parseDouble(cost);
        String price = txtPrice.getText().toString();
        double priceDouble = Double.parseDouble(price);
        //System.out.println(cost);
        String Quantity = txtQuantity.getText().toString();
        Integer QuantityInt = Integer.parseInt(Quantity);
        String unit = jComboBox2.getSelectedItem().toString();
        String number = txtNumber.getText().toString();
        Integer numberInt = Integer.parseInt(number);
        java.util.Date utilDate = new java.util.Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(utilDate);
        cal.set(Calendar.MILLISECOND, 0);
        ProductModel product = new ProductModel();
        CompanyModel companyModel = new CompanyModel();
        companyModel.setName(jComboBox1.getSelectedItem().toString());
        product.setCompanyModel(companyModel);
        product.setProductName(name);
        product.setCost(costdouble);
        product.setPrice(priceDouble);
        product.setQuantity(QuantityInt);
        UnitModel unitModel = new UnitModel();
        unitModel.setUnitName(unit);
        product.setUnitModel(unitModel);
        product.setNumber(numberInt);
        product.setExpiryDate(new java.sql.Timestamp(utilDate.getTime()));
        System.out.println(product.getExpiryDate() + "asdf");
        product.setCreatedBy(LoginFrame.userModel);
        product.setModifiedBy(LoginFrame.userModel);
        product.setCreatedDate(new Timestamp(0));
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        product.setCreatedDate(timestamp);
        product.setModifiedDate(timestamp);
        ProductDAOImpl productObj = new ProductDAOImpl();
        int r = productObj.addProduct(product);
        if (r == 1) {
            JOptionPane.showMessageDialog(rootPane, "Record add successfully");
        } else {
            JOptionPane.showMessageDialog(rootPane, "try again ");

        }
        }
        new ProductViewFrame().setVisible(true);
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabel6 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        txtName = new java.awt.TextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtCost = new java.awt.TextField();
        txtPrice = new java.awt.TextField();
        txtQuantity = new java.awt.TextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtNumber = new java.awt.TextField();
        expiryDateField = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(140, 198, 62));
        jLabel7.setText("Add Product");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(202, 202, 202)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label1.setText("Name");
        jPanel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Company");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        label2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label2.setText("Cost");
        jPanel2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        label3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label3.setText("Price");
        jPanel2.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        label4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label4.setText("Quantity");
        jPanel2.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label5.setText("Unit");
        jPanel2.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        label6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label6.setText("Number");
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 74, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Expiry Date");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 100, 30));

        txtName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 300, 30));

        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 300, 30));

        txtCost.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 300, 30));

        txtPrice.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 300, 30));

        txtQuantity.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 300, 30));

        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 300, 30));

        txtNumber.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 300, 30));

        expiryDateField.setDateFormatString("MMMMM dd, yyyy");
        jPanel2.add(expiryDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 300, 30));

        jLabel2.setBackground(new java.awt.Color(140, 198, 62));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Record");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 160, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        addProduct();
       clearAllFeilds();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductAddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser expiryDateField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.TextField txtCost;
    private java.awt.TextField txtName;
    private java.awt.TextField txtNumber;
    private java.awt.TextField txtPrice;
    private java.awt.TextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private void fillCompanyComboBox() {
        CompanyDAOImpl companyDAOImpl = new CompanyDAOImpl();
    List<CompanyModel> companies = companyDAOImpl.getAllCompany();
    for(CompanyModel list:companies){
    jComboBox1.addItem(list.getName());
    }
    
    
    
    
    }

    private void fillUnitComboBox() {
        UnitDAOImpl  unitDAOImpl = new UnitDAOImpl();
        List<UnitModel> units = unitDAOImpl.getAllUnit();
        for(UnitModel list:units){
        
        jComboBox2.addItem(list.getUnitName());
        }
    
    }
}
