/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pms.frames;

import com.pms.daoimpl.PurchaseDAOImpl;
import com.pms.daoimpl.PurchaseDetailsDaoImpl;
import com.pms.models.PurchaseDetailsModel;
import com.pms.models.PurchaseModel;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Asif Ali
 */
public class ViewPurchase extends javax.swing.JFrame {

    /**
     * Creates new form ViewPurchase
     */
    public ViewPurchase() {
        initComponents();
        fillPurchaseTable();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewPurchaseDetailsTable = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        purchaeNo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DealerName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        remaining = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        discountlabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        amountlabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        commsionlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewPurchaseTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpurchasefield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        ViewPurchaseDetailsTable.setBounds(new java.awt.Rectangle(0, 0, 630, 600));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Purchase No");

        purchaeNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        purchaeNo.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Dealor Name");

        DealerName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DealerName.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Date");

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setText("jLabel8");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Grand Total");

        total.setText("jLabel6");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Remaining");

        remaining.setText("jLabel8");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Discount%");

        discountlabel.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Amount Paid");

        amountlabel.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Commision%");

        commsionlabel.setText("jLabel13");

        javax.swing.GroupLayout ViewPurchaseDetailsTableLayout = new javax.swing.GroupLayout(ViewPurchaseDetailsTable.getContentPane());
        ViewPurchaseDetailsTable.getContentPane().setLayout(ViewPurchaseDetailsTableLayout);
        ViewPurchaseDetailsTableLayout.setHorizontalGroup(
            ViewPurchaseDetailsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPurchaseDetailsTableLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(ViewPurchaseDetailsTableLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(ViewPurchaseDetailsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewPurchaseDetailsTableLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addComponent(purchaeNo))
                    .addComponent(jLabel4)
                    .addGroup(ViewPurchaseDetailsTableLayout.createSequentialGroup()
                        .addGroup(ViewPurchaseDetailsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(ViewPurchaseDetailsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DealerName)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ViewPurchaseDetailsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewPurchaseDetailsTableLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(discountlabel))
                    .addGroup(ViewPurchaseDetailsTableLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amountlabel))
                    .addGroup(ViewPurchaseDetailsTableLayout.createSequentialGroup()
                        .addGroup(ViewPurchaseDetailsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewPurchaseDetailsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remaining)
                            .addComponent(commsionlabel))))
                .addGap(77, 77, 77))
        );
        ViewPurchaseDetailsTableLayout.setVerticalGroup(
            ViewPurchaseDetailsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewPurchaseDetailsTableLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(ViewPurchaseDetailsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(purchaeNo)
                    .addComponent(jLabel8)
                    .addComponent(discountlabel))
                .addGap(18, 18, 18)
                .addGroup(ViewPurchaseDetailsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DealerName)
                    .addComponent(jLabel10)
                    .addComponent(amountlabel))
                .addGap(23, 23, 23)
                .addGroup(ViewPurchaseDetailsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(date)
                    .addComponent(jLabel12)
                    .addComponent(commsionlabel))
                .addGap(18, 18, 18)
                .addGroup(ViewPurchaseDetailsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(total)
                    .addComponent(jLabel6)
                    .addComponent(remaining))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ViewPurchaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ViewPurchaseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewPurchaseTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ViewPurchaseTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PurchaseNo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("ViewPurchase");

        jpurchasefield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpurchasefieldKeyReleased(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpurchasefield, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 894, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(363, 363, 363)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jpurchasefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewPurchaseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPurchaseTableMouseClicked
      
       ViewPurchaseDetailsTable.setVisible(true);
       ViewPurchaseDetailsTable.setLocationRelativeTo(null);
       fillPurchaseDetailsTable();
        Integer months = new PurchaseDetailsDaoImpl().getCommisionMonths(Integer.parseInt( ViewPurchaseTable.getValueAt(ViewPurchaseTable.getSelectedRow(), 0).toString()));
            getRemainingBalance(String.valueOf(ViewPurchaseTable.getValueAt(ViewPurchaseTable.getSelectedRow(), 9)),months);
        
    }//GEN-LAST:event_ViewPurchaseTableMouseClicked

    private void jpurchasefieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpurchasefieldKeyReleased
        String purchase_No = jpurchasefield.getText();
        TableRowSorter  tableRowSorter = new TableRowSorter(ViewPurchaseTable.getModel());
        ViewPurchaseTable.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)"+purchase_No));
    }//GEN-LAST:event_jpurchasefieldKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
       new HomeFrame1().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPurchase().setVisible(true);
            }
        });
    }
    public void fillPurchaseTable(){
     DefaultTableModel defaultTableModel = new DefaultTableModel(){
         @Override
         public boolean isCellEditable(int row, int column) {
             return false; //To change body of generated methods, choose Tools | Templates.
         }    
     };
    defaultTableModel.addColumn("Id");
    defaultTableModel.addColumn("purchaseNo");
    defaultTableModel.addColumn("CompanyName");
    defaultTableModel.addColumn("DealerName");
      defaultTableModel.addColumn("Date");
      defaultTableModel.addColumn("Total");
      defaultTableModel.addColumn("Discount");
      defaultTableModel.addColumn("AmountPaid");
    defaultTableModel.addColumn("Comission");
    defaultTableModel.addColumn("ComissionType");
    defaultTableModel.addColumn("Comment");
    defaultTableModel.addColumn("Created_By");
    defaultTableModel.addColumn("Created_date");
    defaultTableModel.addColumn("Modified_By");
    defaultTableModel.addColumn("Modified_date");
  PurchaseDAOImpl purchaseDAOImpl = new PurchaseDAOImpl();
  List<PurchaseModel> list = purchaseDAOImpl.getPurchaseInfo();
    for(PurchaseModel purchases:list){
    Object purchase[] = {purchases.getPurchaseId(),purchases.getPurchaseNo(),purchases.getCompanyModel().getName(),purchases.getDealorModel().getDealerName(),purchases.getPurchaseDate(),purchases.getTotal(),purchases.getDiscount(),purchases.getAmountPaid(),purchases.getCommisson()    ,purchases.getComissonModel().getCommisionType(),purchases.getComment(),purchases.getCreatedBy().getName(),purchases.getCreatedDate(),purchases.getModifiedBy().getName(),purchases.getModifiedDate()};
            //,purchases.getCompanyModel().getComapanyName(),purchases.getDealorModel().getDealerName(),purchases.getPurchaseDate(),purchases.getTotal(),purchases.getDiscount(),purchases.getAmountPaid(),purchases.getCommisson()    ,purchases.getComissonModel().getCommisionType(),purchases.getComment()};
    defaultTableModel.addRow(purchase);
    }
  ViewPurchaseTable.setModel(defaultTableModel);
    }
public void fillPurchaseDetailsTable(){
 DefaultTableModel defaultTableModel = new DefaultTableModel(){
         @Override
         public boolean isCellEditable(int row, int column) {
             return false; //To change body of generated methods, choose Tools | Templates.
         }    
     };
defaultTableModel.addColumn("Pd_id");
defaultTableModel.addColumn("PurchaseId");
defaultTableModel.addColumn("ProductName");
defaultTableModel.addColumn("Quantity");
defaultTableModel.addColumn("Rate");
defaultTableModel.addColumn("Unit");

int purchaseNo = Integer.parseInt(ViewPurchaseTable.getValueAt(ViewPurchaseTable.getSelectedRow(),1).toString());
purchaeNo.setText(String.valueOf(purchaseNo));
String DealorName = ViewPurchaseTable.getValueAt(ViewPurchaseTable.getSelectedRow(), 3).toString();
DealerName.setText(DealorName);
String Date = ViewPurchaseTable.getValueAt(ViewPurchaseTable.getSelectedRow(), 4).toString();
date.setText(Date);
double discount =(double) ViewPurchaseTable.getValueAt(ViewPurchaseTable.getSelectedRow(), 6);
double amountPaid = (double) ViewPurchaseTable.getValueAt(ViewPurchaseTable.getSelectedRow(), 7);
double commision = (double) ViewPurchaseTable.getValueAt(ViewPurchaseTable.getSelectedRow(), 8);
discountlabel.setText(String.valueOf(discount));
amountlabel.setText(String.valueOf(amountPaid));
commsionlabel.setText(String.valueOf(commision));
        PurchaseDetailsDaoImpl purchaseDetailDAOImpl = new PurchaseDetailsDaoImpl();
System.out.println(purchaseNo);
List<PurchaseDetailsModel> list = purchaseDetailDAOImpl.getAllPurchaseInfo(purchaseNo);
for(PurchaseDetailsModel purchaseDetails:list){
Object items[] = {purchaseDetails.getProductDetailId(),purchaseDetails.getPurchaseModel().getPurchaseId(),purchaseDetails.getProductModel().getProductName(),purchaseDetails.getQuantity(),purchaseDetails.getRate(),purchaseDetails.getUnitModel().getUnitName()};
defaultTableModel.addRow(items);
System.out.println(purchaseDetails.getProductModel().getProductName());
}

jTable2.setModel(defaultTableModel);
total.setText(String.valueOf(getGrandTotal()));
}
private void getRemainingBalance(String commisionType,Integer months){
        
        double discountValue = Double.parseDouble(ViewPurchaseTable.getValueAt(ViewPurchaseTable.getSelectedRow(), 6).toString());
        double amountPaidValue = Double.parseDouble(ViewPurchaseTable.getValueAt(ViewPurchaseTable.getSelectedRow(), 7).toString());
        double comissionValue = Double.parseDouble(ViewPurchaseTable.getValueAt(ViewPurchaseTable.getSelectedRow(), 8).toString());
        
        if(commisionType.equals("monthly")){
            months += 1;
            double totalAmount = Double.parseDouble(String.valueOf(getGrandTotal()));
            double remainingBalance = totalAmount - (totalAmount * (discountValue/100.0));
            remainingBalance = remainingBalance - amountPaidValue;
            remainingBalance = (remainingBalance * (months*(comissionValue/100.0))) + remainingBalance;
            remaining.setText(String.valueOf(remainingBalance));
        }
        else if(commisionType.equals("quarter months")){
            if(months == 0){
		months += 1;
            }

            while(true){
		if(months%3 == 0){
			break;
		}
		months++;
            }
		
		int i = 1;
		int interval = 0;
		
		while(i<=months){
			++interval;
			i+=3;
		}
                
            double totalAmount = Double.parseDouble(String.valueOf(getGrandTotal()));
            double remainingBalance = totalAmount - (totalAmount * (discountValue/100.0));
            remainingBalance = remainingBalance - amountPaidValue;
            remainingBalance = (remainingBalance * (interval*(comissionValue/100.0))) + remainingBalance;
            remaining.setText(String.valueOf(remainingBalance));
        }
        else if(commisionType.equals("six months")){
            if(months == 0){
		months += 1;
            }

            while(true){
		if(months%6 == 0){
			break;
		}
		months++;
            }
		
		int i = 1;
		int interval = 0;
		
		while(i<=months){
			++interval;
			i+=6;
		}
                
            double totalAmount = Double.parseDouble(String.valueOf(getGrandTotal()));
            double remainingBalance = totalAmount - (totalAmount * (discountValue/100.0));
            remainingBalance = remainingBalance - amountPaidValue;
            remainingBalance = (remainingBalance * (interval*(comissionValue/100.0))) + remainingBalance;
            remaining.setText(String.valueOf(remainingBalance));
        }
        else if(commisionType.equals("yearly")){
            if(months == 0){
		months += 1;
            }

            while(true){
		if(months%12 == 0){
			break;
		}
		months++;
            }
		
		int i = 1;
		int interval = 0;
		
		while(i<=months){
			++interval;
			i+=12;
		}
                
            double totalAmount = Double.parseDouble(String.valueOf(getGrandTotal()));
            double remainingBalance = totalAmount - (totalAmount * (discountValue/100.0));
            remainingBalance = remainingBalance - amountPaidValue;
            remainingBalance = (remainingBalance * (interval*(comissionValue/100.0))) + remainingBalance;
            remaining.setText(String.valueOf(remainingBalance));
        }
        
       
        
    }
public double getGrandTotal(){
double totalAmount = 0;
for(int i=0;i<jTable2.getRowCount();i++){
double quantity = Double.parseDouble(jTable2.getValueAt(i, 3).toString());
double total = Double.parseDouble(jTable2.getValueAt(i, 4).toString())*quantity;
totalAmount+=total;
}
return totalAmount;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DealerName;
    private javax.swing.JFrame ViewPurchaseDetailsTable;
    private javax.swing.JTable ViewPurchaseTable;
    private javax.swing.JLabel amountlabel;
    private javax.swing.JLabel commsionlabel;
    private javax.swing.JLabel date;
    private javax.swing.JLabel discountlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jpurchasefield;
    private javax.swing.JLabel purchaeNo;
    private javax.swing.JLabel remaining;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}

